### PR TITLE
joe/rtd2.0

### PR DESCRIPTION
**Pull request by visionjo**
This is a work in progress. Pushing for collaborative development.

### CODE REVIEW

**Comment by visionjo** [comment]
Here is syntax guide, https://myst-parser.readthedocs.io/en/v0.16.1/syntax/syntax.html

Upon reviewing a page, please leave the page name and list as completed, with recommendations below. Surely, some pages will be trivial, while others may take a moment.

Many reviewers, so all take a chunk. Any recommendations or ideas are appreciated, as this still is something to master (i.e., learning as we go).

Please complete by the EOW (i.e., sooner is better, but by Friday 6/2 please.

Thanks!

**Comment by joseph-cooke** [comment]
Welcome page
- Recommendations
  - 'This help system contains the most' -> 'This site contains the most' (help system sounds like it is more than a documentation page or at least it does to me.)
  - 'and instructions on getting an account, connecting to the system, loading modules, running jobs, and storing data.' -> 'and instructions on getting an account, connecting to the HPC system, loading software modules, running jobs, and transferring data.' (Just trying to be a little more explicit in what some of the items were and changed from storing to transferring because the data on the HPC should be utilized for some sort of workflow and not just for storage of data.)
  - 'This help system is updated frequently to reflect the latest information about Discovery, as well as to add new topics to help you with your research. Check back often to view our updates.' -> This site is updated frequently to reflect the latest information about Discovery, as well as to add new topics to help you with your research. Check back often to view our updates.

**Comment by joseph-cooke** [comment]
Getting Help
- Recommendations
  - `Make sure to include details about your question or issue, including any commands or scripts that you are trying to use, so that we can best connect you with the right person to help you.` -> `Make sure to include details about your question or issue, including any commands or scripts that you are trying to use, and slurm jobids or Open OnDemand Session IDs so that we can best connect you with the right person to help you.` (If the researchers give us the slurm job id, we can get the batch script, their environment and many other details and the same goes with the OOD Session IDs. Often times we ask for this information so if they provide this from the start it gives us a running start in some cases.)
  - The boxes for the different tickets look so much better than the list! Just wanted to point that out.

**Comment by joseph-cooke** [comment]
Getting Access - Approved
- Recommendations
  - `PIs, professors, and instructors can sponsor themselves.` Seems redundant because it is listed right above under the `Principal Investigator(PI)/Professor/Instructor Access` section. 
  - Should `Principal Investigator(PI)/Professor/Instructor Access` be a note or important box or in a box like `Valid NU Credentials`?

**Comment by joseph-cooke** [comment]
Software Overview - (Possible improvement if suggestions are agreed upon, if not - all links work) Approved. 
- Recommendations
  - `interactive apps on Open onDemand` -> `interactive apps on Open OnDemand`
  - Should `See [Using Module](https://northeastern-university-rc-public-documentation--51.com.readthedocs.build/en/51/04_software/02_modules.html#using-module) for more information about working with module.` and the other three points be a bulleted list? It is okay as it is but it seems like there might be a better way to present this information. Maybe 4 boxes like with the different ways to get help on the `Getting Help` page? 
  - Should `Using Make` be its own subpage like OOD, Modules, and Spack are? It feels out of place to me and it feels like it could be expanded upon. Make it a proper 1. 2. ... N. list and also add in suggestions like there are normally README or INSTALL text files that offer the steps to compile.

**Comment by joseph-cooke** [comment]
Using Module - Approved (all links work in the page - only point that might want to be considered is the color of the highlighted code block because of the contrast on the light background). 
- Recommendations
  - Is there a different color choice for the highlighted code (ex `which`) because it shows as light red in light mode. Dark mode has enough contrast but it might cause a visibility issue in light mode. (Note sure what others think). 
  - In the Caution note you might want to say `http proxy` -> http/https proxies'

**Comment by joseph-cooke** [comment]
Using MATLAB - Approved
- Recommendations 
  - `Open onDemand` -> `Open OnDemand`
  - `Use the following procedure if you need to install a MATLAB toolbox:` A step should be included that these steps should be completed from a compute node (unzip and running matlab are cpu intensive tasks). 
  - In the `To start MATLAB and add a Cluster Profile, do the following:`, after step 8 there is a breakout block. I think this is okay but something might want to be added to the top of it because it feels disjointed at first. Original RTD has a., b., and c
  - `(OPTIONAL) In the Cluster Profile column, right-click on the TestProfile name and select Set as Default. This sets your profile to be the default.` should be a broken out in a note block.

**Comment by visionjo** [comment]
> 

This should be all set: I went end-to-end improving language on this page. Let me know if there is anything I missed.

**Comment by joseph-cooke** [comment]
On the partition page there is a reference that isn't linked to anything - {ref}`using-slurm’

Is there a way to make tables scroll horizontally? If not we might want to refactor the one table on this page because the title of the one column is 4 lines tall.

**Comment by joseph-cooke** [comment]
On the Using Globus page we have a reference that is broken - See :ref: using_nuendpoint

**Comment by joseph-cooke** [comment]
Under Using OOD’s File Explorer it has $HOME quota being 100 GB

**Comment by joseph-cooke** [comment]
@visionjo  - I just finished looking over the new RTD. Great Job!! I only found two items that seemed to have broken references but everything else looks to be find to push and then we can start the refinement as additional PRs. Thank you!!

**Comment by visionjo** [comment]
@joseph-cooke, fixed broken parts (left cosmetic for the next round, as I like all thoughts)

**Pull request merged**
