### PR TITLE
Delete page Update index.md

### PR DESCRIPTION
**Pull request by tketchem14**

### CODE REVIEW

**Comment by arsalanakhter** [comment]
Not sure if we can or should delete this. Currently it points to the technical info on ways to get started on Mac, Linux and Windows. Not sure if we should move all that info to website.

**Comment by joseph-cooke** [comment]
I think this would have to be moved to the website but not sure if that is the best place since it is more of a guide. How would creating a section under 'User Guides' titled `Connecting to the Cluster` and moving this information there and removing it from Getting Started? I think it being the only item under Getting Started is a little misleading?

**Comment by tketchem14** [comment]
I'm ok with keeping this page if it makes things easier! I might have just gotten a little carried away removing pages :)

**Comment by joseph-cooke** [comment]
I am actually got moving it (which is easy). If we use the RTD as more technical guides, it might be interesting to recast it as a guide to connecting to the cluster. It would fit the line of what goes onto the website and what goes to the RTD. If I am alone on this, I think we can keep it as is also but I think moving it would be fine as well.

**Review by SerenaCaplins — APPROVED** [review]
I moved things around here. So the connecting to cluster is now under user guides. 

I approve these changes. :)

**Pull request merged**
