### PR TITLE
Add lowpriority to software RTD page

### PR DESCRIPTION
**Pull request by ShobanaSekar**

### CODE REVIEW

**Review by gshomo — COMMENTED** [review]
are we sure we want to include 'lowpriority' in conda- and spack-installation documentation ? do we need to document "what to do if you are preempted" ?

**Review by manasvita — CHANGES_REQUESTED** [review]
I agree with @gshomo's assessment that we probably don't need a pre-emptable job for installing a software. So best would be to request a regular partition to avoid installation interruptions.

**Comment by manasvita** [comment]
@ShobanaSekar, this should be all set once the changes are made.

**Review by marianalevineu — APPROVED** [review]
looks good to me, thanks.

**Comment by ShobanaSekar** [comment]
Per discussion with the team, we have decided to not include lowpriority mentions in conda and spack installs. Hence, closing this PR.

**Pull request closed without merging**
