### PR TITLE
Scientific Software Guides Section

### PR DESCRIPTION
**Pull request by suryap649**
- Added a tutorials page for the scientific software section

### CODE REVIEW

**Review by visionjo — COMMENTED** [review]
@suryap649, I like the concept, but I wonder if this goes along with the theme of our long-term intent with this section. I like that you are thinking outside the box, though.

@joseph-cooke, what are your thoughts on organizing it this way?

**Comment by joseph-cooke** [comment]
I like the idea and I think with time this could move to a page of its own but right now, we really only have 3 directories of scripts. I think the only advantage is if this is its own page, we can point to them on lets say the Matlab RTD page or the Schrodinger page (when/if we create one) and the same as we add applications to module or containers. 

I like the idea of keeping this minimalistic because I don't like the idea of explaining too many concepts here and then have to update here and the individual repos if we have to make changes. 

One addition might be a quick step guide on how to clone the repo and get started just for people who are unfamiliar with github. 

@suryap649  and @visionjo, does this sound on par with where we are going? I think the individual repos should be the source of truth and we lean on them.

**Review by visionjo — COMMENTED** [review]
Let's resolve this PR without merging. We spoke during the FTE meeting and decided the TOC was okay.

Please continue to review other pages.

**Comment by visionjo** [comment]
This content is already present in other pages. We have decided to move it there. Closing PR.

**Pull request closed without merging**
