### PR TITLE
Re-create video-windows branch minus docs/build/ .

### PR DESCRIPTION
**Pull request by dhml**
@rschroter, FYI.

### CODE REVIEW

**Review by rschroter — COMMENTED** [review]
This branch is outdated and should NOT be merged into `master`.

**Comment by rschroter** [comment]
@dhml could you create another pull request, just deleting the `docs/build` ?

**Comment by rschroter** [comment]
...and we can just delete the `video-windows` branch.

**Comment by dhml** [comment]
Got it, thanks @rschroter.  I've deleted the branch.

**Pull request closed without merging**
