### PR TITLE
added lowpriority mentions to the checkpointing best practices section.

### PR DESCRIPTION
**Pull request by manasvita**
#23 PR migrating to the scavenger branch

### CODE REVIEW

**Comment by manasvita** [comment]
@marianalevineu, could you address @ShobanaSekar's comments on this PR and get them approved, so that I can merge this branch? Thanks.

**Comment by marianalevineu** [comment]
@manasvita  I'm not able to see any comments by @ShobanaSekar ...not sure where it is...see screenshot.
Screen Shot 2022-11-21 at 11 14 31 PM

**Comment by marianalevineu** [comment]
@manasvita  I've addressed all comments let me know if there's anything else thanks.

**Review by ShobanaSekar — APPROVED** [review]

**Comment by manasvita** [comment]
@marianalevineu, looks good. I'll go ahead and merge this branch to scavenger now.

**Pull request merged**
